#! /usr/bin/env ruby

require 'simlog'
require 'tools'

include Pocosim

io = Logfiles.open(ARGV.shift)
stream = io.stream(ARGV.shift)

data = stream.samples.map do |_, _, data|
    break(data)
end

if data
    STDERR.puts "has #{data.corridors.size} corridors"
    data.to_dot('plan.dot')

    STDERR.puts "starting at c#{data.start_corridor}, end at c#{data.end_corridor}"


    path = [[data.start_corridor, :FRONT_SIDE]]
    traverse(data, path)
    output_path(File.open('plan.csv', 'w'), data, path)

    data
end

