#! /usr/bin/env ruby

require 'pocolog'
require 'corridor_plan'

include Pocolog
io = Logfiles.open(ARGV.shift)
stream = io.stream(ARGV.shift)

data = stream.samples.map do |_, _, data|
    break(data)
end

if data
    pp data.connections
    STDERR.puts "has #{data.corridors.size} corridors"
    File.open('plan.dot', 'w') do |io|
        io.write data.to_dot
    end

    data
end

